config/routes.rb
Rails.application.routes.draw do

	class AdminConstraint
		def matches?(request)
			user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

			User.find_by(id: user_id)&.admin_role?
		end
	end

	scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
		root 'pages#index'

		resources :capitals do 
			collection do 
				get 'completed'
			end
			resources :additions
		end

		resources :wallets do 
			resources :operations
		end

		resources :users, only: %i[new create edit update]
		
		resource :session, only: %i[new create destroy]

		resource :password_reset, only: %i[new create edit update]

		namespace :admin do 
			resources :users, only: %i[index create edit update destroy], constraints: AdminConstraint.new
		end
	end
end

app/models/capital.rb
class Capital < ApplicationRecord
	include Authorship
  has_many :additions, dependent: :destroy
	belongs_to :user

  validates :goal, presence: true, length: { minimum: 3 }
  validates :amount, presence: true, numeric: true
  validates :period, presence: true, numeric: { message: "should be equal to the number of months"}
end

app/controllers/capitals_controller.rb
class CapitalsController < ApplicationController
	before_action :set_capital!, only: %i[show update edit destroy]
	before_action :authorize_capital!
	after_action :verify_authorized

  def new
    @capital = Capital.new 
  end

  def create
    @capital = current_user.capitals.build capital_params

    if @capital.save
      flash[:success] = 'You started saving money'
      redirect_to capitals_path(anchor: "capital-#{@capital.id}")
    else
      render :new
    end
  end

  def index
    capitals_status('not completed')
    @capitals = @capitals.decorate
  end

  def show
    @capital = @capital.decorate 

    @addition = @capital.additions.build
   	@pagy, @additions = pagy @capital.additions.order created_at: :desc
    @additions = @additions.decorate

    @balance = @capital.additions.sum(:balance)
  end

  def edit
  end

  def update
    if @capital.update capital_params
      flash[:success] = 'Goal updated'
      redirect_to capitals_path
    else
      render :edit 
    end
  end

  def destroy
    @capital.destroy
    flash[:success] = 'The goal has been deleted'
    redirect_to capitals_path
  end

  def completed 
    capitals_status('done')
    @capitals = @capitals.decorate
  end

  private

  def capital_params
    params.require(:capital).permit(:goal, :amount, :period, :status)
  end

	def set_capital!
		@capital = Capital.find params[:id]
	end

	def capitals_status(status)
		@pagy, @capitals = pagy Capital.where(status: status, user_id: current_user.id).order(created_at: :desc)
	end

	def authorize_capital!
		authorize(@capital || Capital)
	end
end

app/views/capitals/_capital.html.erb
<article class="card my-3" id="capital-<%= capital.id %>">
	<section class="card-header">
		<time datetime="<%= capital.formatted_created_at %>">
			<small><%= capital.formatted_created_at %></small>		
		</time>
	</section>

	<div class="card-body">

		<h4>Goal: <%= capital.goal %></h4>

		<section class="card-text">
		<%# <progress style="width: 200px; height: 20px" id="progress-bar" value="85" max="100"></progress> %>
			<div class="container">
				<div class="row justify-content-between">
					<div class="col-auto me-auto">
						<p class="my-2">
							Period: <%= capital.period %>
						</p>

						<p class="my-2">
							<!-- strip_tags - убирает html теги, truncate - ограничивает вывод до определенной длины -->
							Amount: <%= capital.amount %> 
						</p>
					</div>
					<div class="col-auto mt-4">
						<%= link_to "Show", capital_path(capital), class: 'btn btn-primary' %>
						<%= link_to "Edit", edit_capital_path(capital), class: 'btn btn-secondary' %>
						<%= link_to "Delete", capital_path(capital), class: 'btn btn-danger', method: :delete, data: {confirm: "Are your sure?"} %>
					<div>
				</div>
			</div>
		</section>
	</div>
</article>

app/views/capitals/_form.html.erb
<%= form_with model: @capital do |f| %>
	<%= render 'shared/errors', object: @capital %>

	<div>
		<div>
			<%= f.label :goal %>
		</div>

		<div>
			<%= f.text_field :goal, placeholder: "Goal", class: "form-control" %>
		</div>
	</div>

	<div>
		<div>
			<%= f.label :amount %>
		</div>

		<div>
			<%= f.number_field :amount %>
		</div>
	</div>

	<div>
		<div>
			<%= f.label :period, "Period (in months)" %>
		</div>

		<div>
			<%= f.number_field :period %>
		</div>
	</div>

	<%= f.submit "Save my money", class: "btn btn-primary" %>

<% end %>

app/views/capitals/completed.html.erb
<% provide :page_title, 'Completed capitals' %>
<% currently_at('Completed') %>

<div class="container text-center">
	<div class="row justify-content-between">
		<div class="col-auto me-auto">
			<h1>Your achieved goals:</h1>
		</div>
		<div class="col-auto">
			<%= link_to "New goal", new_capital_path, class: 'btn btn-primary btn-lg' %>
		</div>
	</div>
</div>

<%= pagination(@pagy) %>
<%= render partial: 'capitals/capital', collection: @capitals, as: :capital %>
<%= pagination(@pagy) %>

app/views/capitals/edit.html.erb
<% provide :page_title, 'Edit capital' %>
<% currently_at('Capitals') %>

<h1>Edit goal</h1>

<%= render 'form' %>

app/views/capitals/index.html.erb
<% provide :page_title, 'Not completed capitals' %>
<% currently_at('Not completed') %>

<div class="container text-center">
	<div class="row justify-content-between">
		<div class="col-auto me-auto">
			<h1>Here are all your current goals</h1>
		</div>
		<div class="col-auto">
			<%= link_to "New goal", new_capital_path, class: 'btn btn-primary btn-lg' %>
		</div>
	</div>
</div>

<%= pagination(@pagy) %>

<%= render partial: 'capitals/capital', collection: @capitals, as: :capital %>

<%= pagination(@pagy) %>

app/views/capitals/new.html.erb
<% provide :page_title, 'New capital' %>
<% currently_at('Capitals') %>

<%= render "form" %>

app/views/capitals/show.html.erb
<% provide :page_title, 'Capital' %>
<% currently_at('Capitals') %>

<article class="card my-3 col-6">
	<section class="card-header">
		<time datetime="<%= @capital.formatted_created_at %>">
			<small><%= @capital.formatted_created_at %></small>		
		</time>
	</section>

	<div class="card-body">

		<h4>Goal: <%= @capital.goal %></h4>

		<section class="card-text">
			<p class="my-2">
				Amount: <%= @capital.amount %>
			</p>

			<p class="my-2">
				<!-- strip_tags - убирает html теги, truncate - ограничивает вывод до определенной длины -->
				Period: <%= @capital.period %> 
			</p>
		</section>
		<% if @balance < @capital[:amount] %>
			<%= link_to "Edit", edit_capital_path(@capital), class: 'btn btn-secondary' %>
			<%= link_to "Delete", capital_path(@capital), class: 'btn btn-danger', method: :delete, data: {confirm: "Are your sure?"} %>
		<% end %>
	</div>
</article>

<% if @balance < @capital[:amount] %>
	<p>
		You can reduce the amount by clicking the button at the bottom.
	</p>

	<%= render 'additions/form' %>

<% else %>
	<h4>
		Congratulations! You have achieved your goal!
	</h4>

	<%= link_to "All completed goals", completed_capitals_path, class: "btn btn-success" %>

  <h5 class="mt-3">
  	Do you want to add a new goal?
  </h5>

  <%= link_to "New goal", new_capital_path, class: "btn btn-primary" %>
	</br>
<% end %>

</br>

<%= pagination(@pagy) %>

<%= render partial: "additions/addition", collection: @additions, as: :addition %>

<%= pagination(@pagy) %>

<% if @balance > 0 %>
	<h4>Total amount: <%= @balance %></h4>
<% end %>