config/routes.rb
Rails.application.routes.draw do

	class AdminConstraint
		def matches?(request)
			user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

			User.find_by(id: user_id)&.admin_role?
		end
	end

	scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
		root 'pages#index'

		resources :capitals do 
			collection do 
				get 'completed'
			end
			resources :additions
		end

		resources :wallets do 
			resources :operations
		end

		resources :users, only: %i[new create edit update]
		
		resource :session, only: %i[new create destroy]

		resource :password_reset, only: %i[new create edit update]

		namespace :admin do 
			resources :users, only: %i[index create edit update destroy], constraints: AdminConstraint.new
		end
	end
end

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
	<div class="alert alert-danger">
		<ul class="mb-0">
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<%  end %>
		</ul>
	</div>
<% end %>

app/views/shared/_menu.html.erb
<% provide :main_menu do %>	
	<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="navbar">
    <div class="container-fluid">
      <li><%= nav_tab "RichPig", root_path, class: "navbar-brand", current_page: current_page  %></li>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Capitals</a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><%= nav_tab "Not completed", capitals_path, class: "dropdown-item", current_page: current_page %>
              <li><%= nav_tab "Completed", completed_capitals_path, class: "dropdown-item", current_page: current_page %>
            </ul>
          </li>
          <li class="nav-item">
            <%= nav_tab "Wallets", wallets_path, class: "nav-link active", current_page: current_page %>
          </li>
					<% if policy([:admin, :user]).index? %>
						<li>
							<%= nav_tab "Users", admin_users_path, class: "nav-link px-2", current_page: current_page %>
						</li>
					<% end %>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Another</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active">FAQ</a>
          </li>
        </ul>

				<ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <li class="dropdown">
            <%= link_to '#', class: 'nav-link px-2 dropdown-toggle text-white',
              data: {"bs-toggle": 'dropdown'} do %>
              <%= tag.div '', class: "flag #{I18n.locale}-flag mt-1" %>
              <!-- название текущей локали -->
              <%= t I18n.locale %>
            <% end %>

            <ul class="dropdown-menu">
              <% I18n.available_locales.each do |locale| %>
                <li>
                  <% if I18n.locale == locale %>
                    <%= tag.span t(locale), class: 'dropdown-item' %>
                  <% else %>
                    <%= link_to t(locale), root_path(locale: locale),
                      class: 'dropdown-item' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>

				<ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
					<% if user_signed_in? %>
						<li class="dropdown">
							<%= link_to '#', class: "nav-link px-2 dropdown-toggle text-white",
								data: {"bs-toggle": "dropdown"} do %>
								<%= image_tag current_user.avatar.variant(resize: "30x30") if current_user.avatar.attached? %>
								<%= current_user.name_or_email %>
							<% end %>
							<ul class="dropdown-menu">
								<li><%= link_to 'Edit profile', edit_user_path(current_user), class: "dropdown-item" %></li>
								<li><hr class="dropdown-divider"></li>
								<li><%= link_to 'Log Out', session_path, class: "dropdown-item", data: {method: :delete} %></li>
							</ul>
						</li>
					<% else %>
						<li>
							<%= nav_tab 'Sign Up', new_user_path, class: "nav-link px-2", current_page: current_page %>
						</li>
						<li>
							<%= nav_tab 'Log In', new_session_path, class: "nav-link px-2", current_page: current_page %>
						</li>
					<% end %>
				</ul>

      </div>
    </div>
  </nav>
<% end %>