config/routes.rb
Rails.application.routes.draw do

	class AdminConstraint
		def matches?(request)
			user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

			User.find_by(id: user_id)&.admin_role?
		end
	end

	scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
		root 'pages#index'

		resources :capitals do 
			collection do 
				get 'completed'
			end
			resources :additions
		end

		resources :wallets do 
			resources :operations
		end

		resources :users, only: %i[new create edit update]
		
		resource :session, only: %i[new create destroy]

		resource :password_reset, only: %i[new create edit update]

		namespace :admin do 
			resources :users, only: %i[index create edit update destroy], constraints: AdminConstraint.new
		end
	end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
	include Authorship
  has_many :operations, dependent: :destroy
	belongs_to :user

	validates :budget, presence: true, numeric: true
	validates :start_date, presence: true
	validates :end_date, presence: true, comparison: {greater_than: :start_date}
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
	before_action :set_wallet!, only: %i[show update edit destroy]
	before_action :require_authentication
	before_action :authorize_wallet!
	after_action :verify_authorized

  def new
    @wallet = Wallet.new
  end

  def create
    @wallet = current_user.wallets.build wallet_params

    if @wallet.save
      flash[:success] = "A new budget has been successfully created"
      redirect_to wallets_path
    else
      render :new
    end
  end

	def show
		@operation = @wallet.operations.build
		@pagy, @operations = pagy @wallet.operations.filter_operations(params[:filter]).order created_at: :desc

		@operations = @operations.decorate
		
		@sum_of_expenses = @wallet.operations.where(operation_type: 'Expense').sum(:operation_amount)
		@balance_of_budget = @wallet[:budget] - @sum_of_expenses

		@diff = (@wallet.end_date.to_date - Time.now.to_date).to_i
	end

  def index
		@pagy, @wallets = pagy Wallet.where(user_id: current_user.id).order(created_at: :desc)
  end

	def destroy
	end

  private

  def wallet_params
    params.require(:wallet).permit(:budget, :start_date, :end_date)
  end

	def set_wallet!
		@wallet = Wallet.find params[:id]
	end

	def authorize_wallet!
		authorize(@wallet || Wallet)
	end
end

app/views/wallets/index.html.erb
<% provide :page_title, 'Wallets' %>
<%  currently_at('Wallets') %>

<div class="container text-center">
	<div class="row justify-content-between">
		<div class="col-auto me-auto">
			<h1>Here are all your current budgets</h1>
		</div>
		<div class="col-auto">
			<%= link_to "New budget", new_wallet_path, class: 'btn btn-primary btn-lg' %>
		</div>
	</div>
</div>

<%= pagination(@pagy) %>

<% @wallets.each do |wallet| %>
	<div class="card mt-3">
		<div class="card-header">
			<%= wallet.start_date %> - <%= wallet.end_date %>
		</div>
		<div class="card-body">
			<h5 class="card-title">Budget for a given period</h5>
			<p class="card-text"><%= wallet.budget %></p>
			<%= link_to "More detailed", wallet_path(wallet), class: 'btn btn-primary' %>
		</div>
	</div>
<% end %>

<%= pagination(@pagy) %>

app/views/wallets/new.html.erb
<% provide :page_title, 'New wallet' %>
<% currently_at('Wallets') %>

<%= form_with model: @wallet do |f| %>
	<%= render "shared/errors", object: @wallet %>

	<div>
		<div>
			<%= f.label :budget %>
		</div>

		<div class="mt-2">
			<%= f.number_field :budget, placeholder: "Budget", class: "form-control" %>
		</div>
	</div>

	<div>
		<div class="mt-2">
			<%= f.label :start_date %>
		</div>

		<div class="mt-2">
			<%= f.date_field :start_date, value: Date.today, min: Date.today %>
		</div>
	</div>

	<div>
		<div class="mt-2">
			<%= f.label :end_date %>
		</div>

		<div class="mt-2">
			<%= f.date_field :end_date %>
		</div>
	</div>

	<%= f.submit "Сreate the budget", class: "btn btn-primary mt-3" %>
<% end %>

app/views/wallets/show.html.erb
<% provide :page_title, 'Wallet' %>
<% currently_at('Wallets') %>

<div>
	<h4>
		The balance of the budget: <%= @balance_of_budget %>
	</h4>
	<% if @diff == 0 %>
		<p style="font-size: 20px">
			Today is the last day of this budget!
		</p>
	<% elsif @diff < 0 %>
		<p style="font-size: 20px">
			The validity period of this budget is over!
		</p>
	<% else %>
		<p style="font-size: 20px">
			<%= @diff %> days left
		</p>
	<% end %>
</div>

<hr style="width: 1000px">

<%= form_with model: [@wallet ,@operation] do |f| %>
	<%= render "shared/errors", object: @operation %>

	<div>
		<div>
			<%= f.label :operation_type, "Type of operation" %>
		</div>

		<div class="mt-2" style="width: 1000px">
			<%= f.select :operation_type, ['Profit', 'Expense'], {include_blank: "Select the type of operation"},
				 {class: 'form-control', required: true} %>
		</div>
	</div>

	<div>
		<div class="mt-2">
			<%= f.label :operation_amount, "Amount" %>
		</div>

		<div class="mt-2" style="width: 1000px">
		<%= f.number_field :operation_amount, placeholder: 'Amount', class: 'form-control' %>
		</div>
	</div>

	<div>
		<div class="mt-2">
			<%= f.label :operation_date, "Date of operation" %>
		</div>

		<div class="mt-2">
			<%= f.date_field :operation_date, value: Date.today, min: @wallet.start_date, max: @wallet.end_date, class: 'form-control-sm' %>
		</div>
	</div>

	<%= f.submit 'Submit', class: 'btn btn-primary mt-3' %>
<% end %>

<hr style="width: 1000px">

<%= form_with url: wallet_path(@wallet), method: :get do |form| %>
	<div class="mt-3 mb-2">
		<%= form.select :filter, ["All transactions", "Profit", "Expense"], {selected: params[:filter]}, {class: "form-select-sm"} %>
		<%= form.submit "Filter", class: 'btn btn-outline-primary btn-sm ' %>
	</div>
<% end %>

<%= pagination(@pagy) %>

<% @operations.each do |operation| %>
	<div class="col-sm">
		<div class="card-body">
			<section class="card-text mb-3">
				<div class="col-sm-9">
					<small><time datetime="<%= operation.formatted_operation_date %>">
						<%= operation.formatted_operation_date %>		
					</time></small>

					<div class="mt-2">
						<% if operation.operation_type == "Profit" %>
							<p class="text-success">+<%= operation.operation_amount %></p>
						<% else %>
							<p class="text-danger">-<%= operation.operation_amount %></p>
						<% end %>
					</div>
				</div>
			</section>
		</div>
	</div>
	<hr style="width: 1000px">
<% end %>

<%= pagination(@pagy) %>