config/routes.rb
Rails.application.routes.draw do

	class AdminConstraint
		def matches?(request)
			user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

			User.find_by(id: user_id)&.admin_role?
		end
	end

	scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
		root 'pages#index'

		resources :capitals do 
			collection do 
				get 'completed'
			end
			resources :additions
		end

		resources :wallets do 
			resources :operations
		end

		resources :users, only: %i[new create edit update]
		
		resource :session, only: %i[new create destroy]

		resource :password_reset, only: %i[new create edit update]

		namespace :admin do 
			resources :users, only: %i[index create edit update destroy], constraints: AdminConstraint.new
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	include Recoverable
	include Rememberable

	enum role: { basic: 0, moderator: 1, admin: 2 }, _suffix: :role

	attr_accessor :old_password, :admin_edit

	has_many :capitals, dependent: :destroy
	has_many :wallets, dependent: :destroy
	has_one_attached :avatar

	has_secure_password validations: false

	validate :correct_old_password, on: :update, if: -> {password.present? && !admin_edit}
	validate :password_presence
	validate :password_complexity
	validates :password, confirmation: true, allow_blank: true,
		length: {minimum: 8, maximum: 70}
	validates :email, presence: true, uniqueness: true, 'valid_email_2/email': true
	validates :role, presence: true
	validate :correct_file_type
	validate :acceptable_image_size

	def author?(obj)
		obj.user == self
	end

	def guest?
		false
	end

	# хешируем наш токен
	def digest(string)
		cost = ActiveModel::SecurePassword.
			min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	private

	def password_complexity
		return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

		msg = 'complexity requirement not met. Length should be 8-70 characters and ' \
          'include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
    errors.add :password, msg
	end

	def password_presence
		errors.add(:password, :blank) unless password_digest.present?
	end

	def correct_old_password
		return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

		errors.add(:old_password, 'is incorrect')
	end

	def correct_file_type
		if avatar.attached? && !avatar.content_type.in?(%w(image/jpeg image/png))
			errors.add(:avatar, 'must be a JPEG or PNG')
		end
	end

	def acceptable_image_size
		if avatar.attached? && avatar.byte_size > 2.megabyte
			errors.add(:avatar, 'is too large')
		end
	end
end

app/controllers/admin/users_controller.rb
module Admin
	class UsersController < BaseController
		before_action :require_authentication
		before_action :set_user!, only: %i[edit update destroy]
		before_action :authorize_user!
		after_action :verify_authorized

		def index
			respond_to do |format|
				format.html do
					@pagy, @users = pagy User.order(created_at: :desc)
				end

				format.zip do
					respond_with_zipped_users
				end
			end
		end

		def edit
		end

		def update
			if @user.update user_params
				flash[:success] = "User updated!"
				redirect_to admin_users_path
			else
				render :edit
			end
		end

		def destroy
			@user.destroy
			flash[:success] = "User deleted!"
			redirect_to admin_users_path
		end

		private 

		def respond_with_zipped_users
			compressed_filestream = Zip::OutputStream.write_buffer do |zos|
				User.order(created_at: :desc).each do |user|
					zos.put_next_entry "user_#{user.id}.xlsx"
					zos.print render_to_string(
						layout: false, handlers: [:axlsx], formats: [:xlsx],
						template: 'admin/users/user',
						locals: {user: user}
					)
				end
			end

			compressed_filestream.rewind
			send_data compressed_filestream.read, filename: 'users.zip'
		end

		def set_user!
			@user = User.find(params[:id])
		end

		def user_params
			params.require(:user).permit(
				:name, :email, :password, :password_confirmation, :role
			).merge(admin_edit: true)
		end

		def authorize_user!
			authorize(@user || User)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_no_authentication, only: %i[new create]
	before_action :require_authentication, only: %i[edit update]
	before_action :set_user!, only: %i[edit update]
	before_action :authorize_user!
	after_action :verify_authorized

	def new
		@user = User.new
	end

	def create
		@user = User.new user_params
		if @user.save
			sign_in(@user)
			flash[:success] = "Welcome to the app, #{current_user.name_or_email}!"
			redirect_to root_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @user.update user_params
			flash[:success] = "You profile was successfully updated!"
			redirect_to root_path
		else
			render :new
		end
	end

	private

	def set_user!
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:email, :name, :password, :password_confirmation, :avatar)
	end

	def authorize_user!
		authorize(@user || User)
	end
end

app/helpers/admin/users_helper.rb
module Admin
	module UsersHelper
		def user_roles
			User.roles.keys.map do |role|
				[ role.titleize, role ]
			end
		end
	end
end

app/views/admin/users/_form.html.erb
<%= form_with model: [:admin, user] do |f| %>
	<%= render 'shared/errors', object: @user %>

	<div class="mb-3 row">
		<div class="col-sm-2 col-form-label">
			<%= f.label :email %>
		</div>

		<div class="col-sm-10">
			<%= f.text_field :email, placeholder: "E-mail", class: "form-control form-control-lg" %>
		</div>
	</div>

	<div class="mb-3 row">
		<div class="col-sm-2 col-form-label">
			<%= f.label :name %>
		</div>

		<div class="col-sm-10">
			<%= f.text_field :name, placeholder: "Name", class: "form-control form-control-lg" %>
		</div>
	</div>

	<div class="mb-3 row">
		<div class="col-sm-2 col-form-label">
			<%= f.label :role %>
		</div>

		<div class="col-sm-10">
			<%= f.select :role, user_roles, {}, class: "form-select form-select-lg" %>
		</div>
	</div>

	<div class="mb-3 row">
		<div class="col-sm-2 col-form-label">
			<%= f.label :password %>
		</div>

		<div class="col-sm-10">
			<%= f.password_field :password, class: "form-control form-control-lg" %>
		</div>
	</div>

	<div class="mb-3 row">
		<div class="col-sm-2 col-form-label">
			<%= f.label :password_confirmation %>
		</div>

		<div class="col-sm-10">
			<%= f.password_field :password_confirmation, class: "form-control form-control-lg" %>
		</div>
	</div>

	<div class="mb-3 row">
		<div class="col-sm-2 col-form-label">
			<%= f.label :old_password %>
		</div>

		<div class="col-sm-10">
			<%= f.password_field :old_password, class: "form-control form-control-lg" %>
		</div>
	</div>

	<%= f.submit (user.new_record? ? "Register" : "Save"), class: "btn btn-primary btn-lg" %>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
	<th scope="row"><%= user.id %></th>
	<td><%= user.name %></td>
	<td><%= user.email %></td>
	<td><%= user.role %></td>
	<td><%= user.created_at %></td>
	<td>
		<%= link_to 'Edit', edit_admin_user_path(user), class: "btn btn-secondary" %>
		<%= link_to 'Delete', admin_user_path(user), class: "btn btn-danger",
			 method: :delete, data: {confirm: "Are you sure?"} %>
	</td>
</tr>

app/views/admin/users/edit.html.erb
<% provide :page_title, 'Edit user' %>
<% currently_at 'Edit' %>

<h1 class="mb-4">Edit user</h1>

<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<% provide :page_title, 'Admin Users' %>
<% currently_at 'Users' %>

<div class="btn-group mb-3">
	<!-- кнопка для выгрузки данных в архив формат XLSX -->
	<%= link_to 'Download zipped XLSX', admin_users_path(format: :zip),
		 class: 'btn btn-secondary', data: {confirm: 'Are you sure?'} %>
</div>

<%= pagination(@pagy) %>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">Name</th>
			<th scope="col">Email</th>
			<th scope="col">Role</th>
			<th scope="col">Created at</th>
			<th scope="col"></th>
		</tr>
	</thead>
	<tbody>
		<%= render @users %>
	</tbody>
</table>

<%= pagination(@pagy) %>